# Generated by Django 4.1.1 on 2022-10-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosPasajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefoniaFull', models.CharField(choices=[['No Desea', 'No Desea'], ['Telenofia Full', 'Telefonia Full']], default='No Desea', max_length=50, verbose_name='Telefonia Full')),
                ('telefoniaLocal', models.CharField(choices=[['No Desea', 'No Desea'], ['Telefonia Local', 'Telefonia Local']], default='No Desea', max_length=50, verbose_name='Telefonia Local')),
                ('desayuno', models.CharField(choices=[['No Desea', 'No Desea'], ['Desayuno', 'Desayuno']], default='No Desea', max_length=50, verbose_name='Desayuno')),
                ('almuerzo', models.CharField(choices=[['No Desea', 'No Desea'], ['Almuerzo', 'Almuerzo']], default='No Desea', max_length=50, verbose_name='Almuerzo')),
                ('cena', models.CharField(choices=[['No Desea', 'No Desea'], ['Cena', 'Cena']], default='No Desea', max_length=50, verbose_name='Cena')),
                ('bar', models.CharField(choices=[['No Desea', 'No Desea'], ['Barra Libre', 'Barra Libre']], default='No Desea', max_length=50, verbose_name='Bar')),
                ('miniBar', models.CharField(choices=[['No Desea', 'No Desea'], ['Mini Bar', 'Mini Bar']], default='No Desea', max_length=50, verbose_name='Mini Bar')),
                ('lavanderia', models.CharField(choices=[['No Desea', 'No Desea'], ['Lavanderia', 'Lavanderia']], default='No Desea', max_length=50, verbose_name='Lavanderia')),
                ('planchado', models.CharField(choices=[['No Desea', 'No Desea'], ['Planchado', 'Planchado']], default='No Desea', max_length=50, verbose_name='Planchado')),
                ('dni', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.pasajero', verbose_name='DNI')),
            ],
        ),
    ]
