# Generated by Django 4.1.1 on 2022-10-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_facturapasajero_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturapasajero',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='facturapasajero',
            name='formaPago',
            field=models.CharField(choices=[['efectivo', 'efectivo'], ['Debito', 'Debito'], ['Tarjeta Credito', 'Tarjeta Credito']], default='No Desea', max_length=50, verbose_name='Forma Pago'),
        ),
    ]
